config/routes.rb
Rails.application.routes.draw do
  root to: 'restaurants#index'

  resources :restaurants, only: [:index, :new, :create, :show] do
    resources :reviews, only: [:new, :create]
  end
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :reviews, dependent: :destroy

  validates_presence_of :name, :address
  validates :category, inclusion: { in: %w(chinese italian japanese french belgian) }
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :restaurant

  validates_presence_of :restaurant, :content, :rating

  validates :rating, inclusion: { in: (0..5).to_a }, numericality: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.valid?
      @restaurant.save
      redirect_to @restaurant
    else
      render 'new'
    end
  end

private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_restaurant, only: [:new, :create]

  def new
    @review = Review.new
  end

  def create
    sanitize_params
    @review = @restaurant.reviews.build(review_params)
    if @review.valid?
      @review.save
      redirect_to @restaurant
    else
      render 'new'
    end
  end

private

  def find_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end

  def sanitize_params
    params[:review][:rating] = params[:review][:rating].to_i
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title Lacuillere
    meta name="viewport" content="width=device-width, initial-scale=1"
    meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    = render 'shared/navbar'
    #body-wrap
      = yield
    = render 'shared/footer'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true

app/views/restaurants/_form.slim
= simple_form_for restaurant, html: { class: 'form' } do |f|
  = f.input :name
  = f.input :address
  = f.input :phone_number
  = f.input :category, collection: %w(chinese italian japanese french belgian)
  .form-group
    = f.button :submit, class: 'btn btn-primary'

app/views/restaurants/_restaurant.slim
.col-md-4
  .card
    span.card-bg style="background-image: url('https://unsplash.it/200/300');"
    span.card-shadow
    span.card-description = restaurant.category
    span.card-text
      h2 = restaurant.name
      p = restaurant.phone_number
    = link_to restaurant_path(restaurant), class: 'card-link'
      '

app/views/restaurants/_review.slim
.post
  .post-body
    h3
      - i = 1
      - 5.times
        - if i <= review.rating
          i.fa.fa-star.colored
        - else
          i.fa.fa-star.uncolored
        - i += 1
    p = review.content

app/views/restaurants/index.html.slim
.container
  .row
    .text-center.padded
      h1 Where do you want to eat ?
    - @restaurants.each do |restaurant|
      = render "restaurant", restaurant: restaurant
  .row
    .col-md-12
      .text-center.padded
        h3 Didn't find your restaurant ?
        = link_to 'Add your restaurant', new_restaurant_path, class: 'navbar-wagon-item navbar-wagon-button btn'

app/views/restaurants/new.html.slim
.container
  .row
    .col-md-12
      h1 Add a new restaurant
      hr
  .row
    .col-md-8
      = render 'form', restaurant: @restaurant

app/views/restaurants/show.html.slim
.banner.text-center style=("background-image: url('https://unsplash.it/800/200')")
  .banner-shadow
  .banner-content
    h1 = @restaurant.name
    p
      'Cooking :
      = @restaurant.category
    = link_to 'Add a review', new_restaurant_review_path(@restaurant), class: 'btn btn-primary btn-lg'

.container
  .row
    .col-md-8.padded
      - if @restaurant.reviews.any?
        - @restaurant.reviews.each do |review|
          = render 'review', review: review
      - else
        p
          'There is no reviews for this restaurant yet. Just try it and give us your feedbacks.
          br
          strong Bon appétit!
      = link_to 'Add a review', new_restaurant_review_path(@restaurant), class: 'btn btn-primary btn-md'

    .col-md-4.padded
      .panel.panel-default
        .panel-heading Contact
        .panel-body
          p
            i.fa.fa-map-marker
            = @restaurant.address
          p
            i.fa.fa-phone
            = @restaurant.phone_number

app/views/reviews/new.html.slim
.banner.text-center style=("background-image: url('https://unsplash.it/800/200')")
  .banner-shadow
  .banner-content
    h1 = @restaurant.name
    p
      'Cooking :
      = @restaurant.category
    = link_to 'Back to the restaurant', restaurant_path(@restaurant), class: 'btn btn-primary btn-lg'

.container
  .row
    .col-md-8.padded
      h3 What do you think ?
      br
      = simple_form_for [@restaurant, @review], html: { class: 'form' } do |f|
        = f.input :content
        = f.input :rating, collection: 0..5
        = f.button :submit, class: 'btn btn-primary'

    .col-md-4.padded
      .panel.panel-default
        .panel-heading Contact
        .panel-body
          p
            i.fa.fa-map-marker
            = @restaurant.address
          p
            i.fa.fa-phone
            = @restaurant.phone_number

app/views/shared/_footer.slim
.wave
footer
  .text-center.padded
    h4 That's how we put boxes Romain !
    h5
      'Made with
      i.fa.fa-heart
      'by the intendant

app/views/shared/_navbar.slim
nav.navbar-wagon
  .container.navbar-wagon-container
    = link_to root_path
        = image_tag('logo.png', class: 'navbar-wagon-logo')
    .navbar-wagon-links
      .navbar-wagon-item-container
        = link_to 'View all restaurants', restaurants_path, class: 'navbar-wagon-item navbar-wagon-link'
        = link_to 'Add a restaurant', new_restaurant_path, class: 'navbar-wagon-item navbar-wagon-button btn'